stages:
  - prepare
  - test

image: thecodingmachine/php:8.0-v4-slim-cli

prepare-dependencies:
  stage: prepare
  script:
    - "composer install"
  artifacts:
    name: "prepare-dependencies"
    expire_in: 45 minutes
    paths:
      - vendor

test:
  stage: test
  dependencies:
    - prepare-dependencies
  script:
    - "./vendor/bin/psalm --inits"
    - "./vendor/bin/psalm --show-info=true"
    - "./vendor/bin/phpcs --standard=PSR12 src public/index.php"
    - "./vendor/bin/phpunit tests"
